# Generated by Django 4.1.3 on 2022-11-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('SName', models.CharField(max_length=30)),
                ('Reg_No', models.IntegerField(primary_key=b'I01\n', serialize=False)),
                ('Address', models.CharField(max_length=60)),
                ('Taluka', models.CharField(max_length=30)),
                ('District', models.CharField(max_length=30)),
                ('State', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujrat')], default='AP', max_length=20)),
                ('Photo', models.ImageField(upload_to='uploads')),
                ('Pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=50)),
                ('Mark', models.IntegerField()),
                ('Semester', models.CharField(max_length=5)),
                ('Year', models.CharField(max_length=10)),
                ('Reg_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('FeedBck', models.CharField(max_length=500)),
                ('Regis_No', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.marks')),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(max_length=10)),
                ('Branch', models.CharField(max_length=30)),
                ('Year', models.CharField(max_length=10)),
                ('DateOfAddmission', models.DateField()),
                ('Semester', models.CharField(max_length=5)),
                ('StudName', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.PROTECT, related_name='student_name', to='student.student')),
                ('reg_Num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reg_number', to='student.student')),
            ],
        ),
    ]
